# Generated by Django 4.1.7 on 2023-03-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=100)),
                ("product_Category", models.CharField(default="", max_length=150)),
                ("product_brand_name", models.CharField(default="", max_length=200)),
                ("product_img", models.ImageField(default="", upload_to="prod/images")),
            ],
        ),
    ]
